### ISSUE TITLE
ZF2 tablegateway Update dangerous!!!

### ISSUE THREAD

**Issue by netroby** [zendframework/zendframework#7595] opened 2015-06-25 09:16 UTC
ZF2 tablegateway Update dangerous!!!

We occurs problem when using TableGateway.

Think about a normal code:

```
$tableGateWay->update(['age' = 12], $id);
```

Oh, no, holly shit. all the table record been overwriten .

And the Zend Framework Db can not detect and prevent the dangerous usage.

Yeah, you killed me.

**Comment by Bittarman** [comment] 2015-06-25 09:36
But this is the expected behaviour for running an update with a where predicate which would resolve for every row.

Yes its bad when you get it wrong, but thats no different from running an update like *UPDATE foo SET bar=1 WHERE 1;* The problem really is in the understanding of how this works. 

I'm adding a label for needs documentation, as I don't think this really needs any code changes.

**Comment by froschdesign** [comment] 2015-06-25 09:39
> I'm adding a label for needs documentation, as I don't think this really needs any code changes.

:+1:

**Comment by netroby** [comment] 2015-06-25 09:53
The type mistake will destory the whole table, I am very sad, I shoot on my feet. hope you guys never face this situation like me.

**Comment by netroby** [comment] 2015-06-25 09:57
No safe guarantee, no lucky

**Comment by netroby** [comment] 2015-06-25 10:00
I suggest , we should check if an update have a where query parameters. If no , throw exception and stop.  Save our life , from got big damage to our database. We will no chance to save our work if we made a small mistake. Very expensive , very hard effort.

**Comment by netroby** [comment] 2015-06-25 10:01
I almost destroyed my company by this accident.

**Comment by Bittarman** [comment] 2015-06-25 10:02
Absolutely not, having no where clause is perfectly valid, we can't make a BC break which makes a perfectly normal valid operation impossible.

**Comment by netroby** [comment] 2015-06-25 10:32
Can we add one more SafeTableGateway ?

code like this :+1: 
```
<?php
namespace com\netroby;

use \Zend\Db\TableGateway\TableGateway;

use Zend\Db\Adapter\AdapterInterface;
use Zend\Db\ResultSet\ResultSetInterface;
use Zend\Db\Sql\Sql;

class SafeTableGateway extends TableGateway
{
    /**
     * Constructor
     *
     * @param string|TableIdentifier|array                                              $table
     * @param AdapterInterface                                                          $adapter
     * @param Feature\AbstractFeature|Feature\FeatureSet|Feature\AbstractFeature[]|null $features
     * @param ResultSetInterface|null                                                   $resultSetPrototype
     * @param Sql|null                                                                  $sql
     *
     * @throws Exception\InvalidArgumentException
     */
    public function __construct($table, AdapterInterface $adapter, $features = null, ResultSetInterface $resultSetPrototype = null, Sql $sql = null)
    {
        parent::__construct($table, $adapter, $features = null, $resultSetPrototype = null, $sql = null);
    }
    /**
     * Delete
     *
     * @param  Where|\Closure|string|array $where
     * @return int
     */
    public function delete($where)
    {
        if (is_string($where) || is_numeric($where) || is_bool($where)) {
            throw new \InvalidArgumentException("Not allowd string|int|bool here");
        }
        return parent::delete($where);
    }

    /**
     * Update
     *
     * @param  array $set
     * @param  string|array|\Closure $where
     * @return int
     */
    public function update($set, $where = null)
    {
        if (is_string($where) || is_numeric($where) || is_bool($where)) {
            throw new \InvalidArgumentException("Not allowd string|int|bool here");
        }
        return parent::update($set, $where);
    }
}
```

**Comment by netroby** [comment] 2015-06-25 10:32
This will help who have the same trouble like me, save our life.

**Comment by DASPRiD** [comment] 2015-06-25 10:42
You are free to use such a class in your own codebase. There is no need to bring something like that into the ZF core.

**Comment by froschdesign** [comment] 2015-06-25 10:51
> Can we add one more SafeTableGateway ?

No, because a string is allowed. (Also in your code example -> DocBlock!)

```php
$table->update(['foo' => 'bar'], 'id = 2');
```
This will be passed as an expression.

> …save our life.

Tests will save your life.

**Comment by netroby** [comment] 2015-06-25 11:42
Thanks your times

**Comment by Bittarman** [comment] 2015-06-25 11:43
This is really a valid documentation issue, I've looked at the relevant docs and it does not seem very well covered at all

**Comment by froschdesign** [comment] 2015-06-25 11:46
> This is really a valid documentation issue

Right!

**Comment by savannahparis** [comment] 2015-12-21 01:00
I have a response for you $table->update(['foo' => 'bar'], array('id' => 2)); this ok
when before you instance $dbAdapter and $tableGateway. It's work very well.

**Comment by nuxwin** [comment] 2015-12-21 01:17
Well, such mistake should happen in development environments only, where the database should be fully recoverable (testing database). This is an API usage mistake, nothing more. If we start to document every possible mistake that the developer can do, we will lost a lot of time.

To resume, that issue should be put in the box of complaints about  the `poor` ZF documentation. Generally, those complaints come from users that are not happy because they must think instead of copy/past code from the documentation. Having a documentation strickly based on specifications is much better from my point of view because the developers must really learn before doing anything by closing eyes.

**Comment by netroby** [comment] 2015-12-21 02:05
I guess document useless. the problems  will be all the time during coding. Even you have document, but you will forgot it sometimes. Like you drunk or drugs too much. so we have to put a strict ,limit the api behaviour. to prevent bad things happen.

**Comment by zf2timo** [comment] 2015-12-21 07:23
To Change all entries in a DB is an absolutely valid use case and the Framework should not catch things like this.
You can't even define `bad things`. In your project changing the age of all persons to 12 is maybe a bad thing  - but in in other projects its maybe useful to mark all entries in a table as invalid.

So a Framework is a toolbox. And if you want to smash your fingers with a hammer, you can do that. Think about what you are doing, and you will be fine.

**Comment by GeeH** [comment] 2016-06-28 12:51
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-db/issues/123

**Closed by GeeH** 2016-06-28 12:51 UTC
Labels: Db, Needs Documentation

**Comment by ruwanthalk** [comment] 2017-02-24 06:19
I paid a big price for similar issue(where close not defined/passed only one array). This is must to be fixed

**Comment by froschdesign** [comment] 2017-02-24 10:47
@ruwanthalk 
You can do the same with plain PHP and it is a valid use case.

We will add a notice in documentation.

**Comment by macnibblet** [comment] 2017-02-24 13:22
@ruwanthalk Tests.
