### ISSUE TITLE
Oracle Improvments / Fixes

### ISSUE THREAD

**Issue by ralphschindler** [zendframework/zendframework#3615] opened 2013-01-30 15:50 UTC
1. Connection::getCurrentSchema() needs to return the user name, not the db name

2. Persistent connections ```$connectionFuncName = ($this->_config['persistent'] == true) ? 'oci_pconnect' : 'oci_connect';```

3. Charset support for connection

4. Better type based parameter binding support (fixed SQLT_LONG in 7664408)

    a. ParameterContainer::TYPE_BINARY for SQLT_BIN oracle datatype
    
5. Remove : prefix in ```oci_bind_by_name```

6. Add support for ```oci_set_client_identifier```

7. Add support for ```oci_set_client_info/oci_set_action/oci_set_module_name```

8. Add support for ```oci_set_prefetch```

**Comment by weierophinney** [comment] 2015-02-10 22:23
One note: if anybody on this thread wants to see any of these fixes... please submit PRs, one per feature. The issue is a placeholder to indicate what features still need some attention.

**Comment by GeeH** [comment] 2016-06-27 21:42
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Closed by GeeH** 2016-06-27 21:42 UTC
Labels: Db, To Be Closed
