### ISSUE TITLE
Http Client with Curl / default adapter and transfer-encoding chunked: Error parsing body - doesn't seem to be a chunked message

### ISSUE THREAD

**Issue by lucian303** [zendframework/zendframework#7683] opened 2016-03-09 17:15 UTC
Once I set the adapter to Socket, it works, but with Curl or the default adapter (which I assume is Curl), I get this message on chunked encodings. From looking at other tickets and my own experience with prior Zend versions, it looks like the Socket adapter used to be unable to handle the chunked transfer encoding while the Curl one was able to and now that has flipped in ZF 2.5.3. In 2.2.10 for example, I'm 99.9% sure it's the other way.

**Comment by marcelto** [comment] 2016-03-09 19:13
This may not be relevant but in the past I've found that curl sometimes has trouble with chunked responses.  To work around the issue I had to set the HTTP version to 1.0.

`curl_setopt($ch, \CURLOPT_HTTP_VERSION, \CURL_HTTP_VERSION_1_0);`

**Comment by lucian303** [comment] 2016-03-09 19:52
So I did more investigation and found the culprit in Zend\Http\Client\Adapter\Curl.php:437:

`$responseHeaders = preg_replace("/Transfer-Encoding:\s*chunked\\r\\n/", "", $responseHeaders);`

Should be:

`$responseHeaders = preg_replace("/Transfer-Encoding:\s*chunked\\r\\n/i", "", $responseHeaders);`

Notice the 'i' in the regex. It should be a case insensitive match as HTTP headers are case insensitive: https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html

**Comment by lucian303** [comment] 2016-03-09 20:12
See pull request: https://github.com/zendframework/zend-http/pull/53

**Comment by sgehrig** [comment] 2016-05-03 14:30
Isn't that a duplicate of https://github.com/zendframework/zend-http/issues/19

**Comment by GeeH** [comment] 2016-06-28 12:34
This issue has been moved from the `zendframework` repository as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html
New issue can be found at: https://github.com/zendframework/zend-http/issues/65

**Closed by GeeH** 2016-06-28 12:34 UTC
Labels: Http

**Comment by ezimuel** [comment] 2016-08-04 15:59
Fixed in zendframework/zend-http#53.
