### ISSUE TITLE
Allowed memory size exhausted in Zend/InputFilter/BaseInputFilter.php when using multiple fieldsets with InputFilterSpecification

### ISSUE THREAD

**Issue by webdevilopers** [zendframework/zendframework#5039] opened 2013-08-28 08:09 UTC
I am not sure if this is an issue on InputFilterSpecification. Maybe the following form uses bad attempts for implementing service and object manager which causes the exhausted memory size in ZF2 2.3.0dev:

Main form:
```
<?php
namespace Matrix\Form;

use Zend\Form\Form;

class CreateBusiness extends Form
{
    public function __construct()
    {
    	parent::__construct('create_business');
    }

    public function init()
    {
        $this->add(array(
            'type' => 'BusinessFieldset',
            'options' => array(
                'use_as_base_fieldset' => true
            )
        ));

        $this->add(array(
            'name' => 'submit',
        	'type' => 'submit',
        	'options' => array(
        		'primary'    => true,
        	),
            'attributes' => array(
                'value' => 'Save',
            ),
        ));
    }
}
```

The BusinessFieldset:
```
<?php
namespace Matrix\Form;

use Matrix\Entity\Business;
use Zend\Form\Fieldset;
use Zend\InputFilter\InputFilterProviderInterface;
use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use Doctrine\Common\Persistence\ObjectManager;
use DoctrineORMModule\Stdlib\Hydrator\DoctrineEntity as DoctrineHydrator;

class BusinessFieldset extends Fieldset
	implements
		InputFilterProviderInterface,
		ServiceLocatorAwareInterface,
		ObjectManagerAwareInterface
{
	protected $serviceLocator;
	protected $objectManager;

	public function setServiceLocator(ServiceLocatorInterface $serviceLocator)
	{
		$this->serviceLocator = $serviceLocator;
	}

	public function getServiceLocator()
	{
		return $this->serviceLocator;
	}

	public function setObjectManager(ObjectManager $objectManager)
	{
		$this->objectManager = $objectManager;
	}

	public function getObjectManager()
	{
		return $this->objectManager;
	}

	public function __construct()
	{
		parent::__construct('business');
	}

	public function init()
	{
		$om = $this->getObjectManager();

		$this->setHydrator(new DoctrineHydrator($om, 'Matrix\Entity\Business'))
			->setObject(new Business());

		$sm = $this->getServiceLocator();

		$sl = $sm->getServiceLocator();
		$authorize = $sl->get('BjyAuthorize\Service\Authorize');

		$this->add(array(
			'name' => 'name',
			'type' => 'text',
			'options' => array(
				'label' => 'Name'
			),
			'attributes' => array(
				'required' => 'required',
				'autofocus' => 'autofocus',
			),
		));

		if ($authorize->isAllowed('matrix-business', 'liquidationDate')) {
			$this->add(array(
				'name' => 'liquidationDate',
				'type' => 'text',
				'options' => array(
					'label' => 'Liquidation'
				),
			));
		}

		$this->add(array(
			'type' => 'objectselect',
			'name' => 'country',
			'options' => array(
				'object_manager' => $this->getObjectManager(),
				'target_class'   => 'Application\Entity\Country',
			),
			'attributes' => array(
				'required' => 'required',
				'value' => 80,
			)
		));

        $this->add(array(
            'type' => 'LiabilityFieldset',
        	'name' => 'liability',
            'options' => array(
            	'label' => 'Liability'
            )
        ));
	}

	public function getInputFilterSpecification()
	{
		return array(
			'name' => array(
				'required' => true,
			),
		);
	}
}
```

The LiabilityFieldset:
```
<?php
namespace Matrix\Form;

use Matrix\Entity\Liability;
use Zend\Form\Fieldset;
use Zend\InputFilter\InputFilterProviderInterface;
use Zend\ServiceManager\ServiceLocatorAwareInterface;
use Zend\ServiceManager\ServiceLocatorInterface;
use DoctrineModule\Persistence\ObjectManagerAwareInterface;
use Doctrine\Common\Persistence\ObjectManager;
use DoctrineORMModule\Stdlib\Hydrator\DoctrineEntity as DoctrineHydrator;

class LiabilityFieldset extends Fieldset
	implements
		InputFilterProviderInterface, // memory size exhausted
		ServiceLocatorAwareInterface,
		ObjectManagerAwareInterface
{
	protected $serviceLocator;
	protected $objectManager;

	public function setServiceLocator(ServiceLocatorInterface $serviceLocator)
	{
		$this->serviceLocator = $serviceLocator;
	}

	public function getServiceLocator()
	{
		return $this->serviceLocator;
	}

	public function setObjectManager(ObjectManager $objectManager)
	{
		$this->objectManager = $objectManager;
	}

	public function getObjectManager()
	{
		return $this->objectManager;
	}

	public function __construct()
	{
		parent::__construct('liability');
	}

	public function init()
	{
 		$om = $this->getObjectManager();

		$this->setHydrator(new DoctrineHydrator($om, 'Matrix\Entity\Liability'))
			->setObject(new Liability());

		$sm = $this->getServiceLocator();

		$sl = $sm->getServiceLocator();
		$authorize = $sl->get('BjyAuthorize\Service\Authorize');

		if ($authorize->isAllowed('matrix-liability', 'capitalStock')) {
			$this->add(array(
				'name' => 'capitalStock',
				'type' => 'text',
				'options' => array(
					'label' => 'Capital stock'
				),
				'attributes' => array(
					#'required' => 'required',
				)
			));
		}
	}

	public function getInputFilterSpecification()
	{
		return array(
			'capitalStock' => array(
				'validators' => array(
					array(
						'name' => 'Float'
					)
				)
			),
		);
	}
}
```

I left out some elements and other fieldsets that use the service and object manager too. But they do not implement the InputFilterProviderInterface. When I remove it from the liabilityFieldset everything is fine. As soon as I re-implement it the memory usage is exhausted.

Maybe it should be added that I use the DluTwBootstrap module to render the elements with Twitter Bootstrap. A view script would look like this:
```
			<?php if ($this->isAllowed('matrix-business', 'liquidationDate')): ?>
				<?php echo $this->formRowTwb($business->get('liquidationDate'),
					\DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL, array(
					'prependIcon' => 'icon-eye-open')); ?>
			<?php endif; ?>
```

I am not sure if this module adds validation on top?

**Comment by dfiloni** [comment] 2015-05-28 07:43
I confirm I can still reproduce this issue in 2.4.*. The fix suggested by @richardjennings works fine, can you please commit it?

**Comment by GeeH** [comment] 2015-05-28 07:49
Please create a PR and I will review.

**Comment by richardjennings** [comment] 2015-06-06 16:25
@GeeH @dfiloni from memory this issue is a recursive dependency between DI and Service Manager and did not look easy to fix. The example I gave above sidesteps the issue but is not a fix.

**Comment by dfiloni** [comment] 2015-06-08 09:33
Yes, looks like this issue is not easily fixable.

I'm using following config as workaround (may be useful to others too):

    /* Zend Di fixes */
    'view_helpers' => array (
        'invokables' => array (
            'form' => 'Zend\Form\View\Helper\Form',
            'formCollection' => 'Zend\Form\View\Helper\FormCollection',
        )
    ),
    'input_filters' => array (
        'invokables' => array (
            'zendinputfilterinputfilter' => 'Zend\InputFilter\InputFilter'
        )
    ),
    'validators' => array (
        'invokables' => array (
            'zendvalidatorfilemimetype' => 'Zend\Validator\File\MimeType',
            'zendvalidatorfileextension' => 'Zend\Validator\File\Extension',
        )
    ),
    'form_elements' => array(
        'invokables' => array(
            'doctrinemoduleformelementobjectselect' => 'DoctrineModule\Form\Element\ObjectSelect'
        )
    )

**Comment by GeeH** [comment] 2016-06-27 19:25
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Closed by GeeH** 2016-06-27 19:25 UTC
Labels: InputFilter, To Be Closed
