### ISSUE TITLE
Segment route always renders optional params if route has childs

### ISSUE THREAD

**Issue by write2art** [zendframework/zendframework#6697] opened 2014-09-25 11:45 UTC
Consider the following router setup:

```php
'route' => [
    'type' => 'Segment',
    'options' => [
        'route'    => '[/:lang]/myaction',
        'constraints' => [
            'lang' => '(ru|en)',
        ],
        'defaults' => [
            'controller'    => 'Application\Controller\My',
            'action'        => 'myaction',
            'lang'          => 'en',
        ],
    ],
    'may_terminate' => true,
    'child_routes' => [
        'child' => [
            'type'    => 'Literal',
            'options' => [
                'route'    => '/child',
                'defaults' => [
                    'action' => 'child',
                ],
            ],
        ],
    ],
]
```

During module bootstrap, i get my locale and set it as default lang param for router like this:
```php
$e->getRouter()->setDefaultParam('lang', $lang);
```

If i set $lang equals to default param value (en), i receive:

```php
$this->url('route'); 
// returns /myaction
$this->url('route/child');  
// returns /en/myaction/child
```

This behavior defined in this line of the Segment router:
```php
elseif (!$isOptional || $hasChild || !isset($this->defaults[$part[1]]) || $this->defaults[$part[1]] !== $mergedParams[$part[1]]) {
    $skip = false;
}
```

So, if a route has child routes it will always render optional default params. What is the reason behind such behavior? Why is it done like this?

**Comment by shipleyr** [comment] 2015-03-04 11:33
I've had the same problem and based on the work of @towr I've created a module which contains a SegmentRouter. It takes an additional config key and skips the relevant sections in the route if no parameter is passed. https://github.com/tccltd/TccSkippableSegment.

**Comment by whitakerbrand** [comment] 2015-04-06 16:58
Is there any reason that shipleyr's (towr's?) changes can't be rolled into the Segment router? I think his subclass assumes all parameters are skippable by default, which doesn't match up with current behavior -- it may make more sense to whitelist every skippable param?

**Comment by towr** [comment] 2015-04-06 18:06
@whitakerbrand I'm pretty sure (though it's been a while) that parameters are *not* assumed to be skippable by default, and that they have to be explicitly marked as skippable. So that should match the desired default behaviour.

**Comment by whitakerbrand** [comment] 2015-04-06 18:32
(Hunh... yeah, I was misunderstanding several things.)

@towr, I don't understand this part of the buildPath() function, in the switch case(parameter) block:
```
                    if (!empty($this->skippable[$part[1]]) && (!isset($mergedParams[$part[1]]) 
                    || !isset($this->defaults[$part[1]]) 
                    || $mergedParams[$part[1]] === $this->defaults[$part[1]])) {
                        // skip this param                       
                        $this->assembledParams[] = $part[1];
                        break;
```

The logic here is:
* if the param was defined to be skippable and it wasn't set in mergedParams, OR
* if there is no default value for the param, OR
* if the merged param value matches the default

Then skip the param.

But that doesn't make sense to me. I feel like I want:

```
                    if (!empty($this->skippable[$part[1]]) && (!isset($mergedParams[$part[1]]) ||
                        array_key_exists($part[1], $this->defaults) && $mergedParams[$part[1]] === $this->defaults[$part[1]])) {
                        // skip this param                       
                        $this->assembledParams[] = $part[1];
                        break;
```

That is to say:
* if the param was marked as skippable and it wasn't set in mergedParams, OR,
* there was a default value and the merged param is the same as the default

Then skip it. 

 Why would I want to fall into the skipping section when there is no default value for the param?

**Comment by whitakerbrand** [comment] 2015-04-06 18:36
(PS thanks for making this -- it is exactly what I needed.)

**Comment by towr** [comment] 2015-04-07 06:24
@whitakerbrand I think you're right. It must always have gone right for me because I've always used defaults.

**Comment by shipleyr** [comment] 2015-04-07 08:23
If you'd like to make a fix to the module I created feel free to create a PR to the repo and if it works I'm more than happy to merge any changes that don't break any thing. I should probably spend time creating a test suite for it but as always... never enough time!

**Comment by whitakerbrand** [comment] 2015-04-08 01:37
@shipleyr Done.

**Comment by mtudor** [comment] 2015-04-10 12:39
Just for future reference, as @whitakerbrand said, I've just tested and confirmed the case in which this would previously have broken:

    - Parameter passed in mergedParams (e.g. from url view helper passing route parameters)
    - No default specified for parameter in route config

In this case, the parameter is always skipped when generating a URL, even though it shouldn't be because we've passed in a specific parameter which should be included in the URL.

And I can confirm that the PR has fixed this.

**Comment by GeeH** [comment] 2016-06-27 14:54
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Closed by GeeH** 2016-06-27 14:54 UTC
Labels: enhancement, Mvc, To Be Closed
