### ISSUE TITLE
Date validator bug

### ISSUE THREAD

**Issue by svycka** [zendframework/zendframework#6406] opened 2014-06-23 13:00 UTC
Validator ignores format when integer provided as data
```php
$validator = new \Zend\Validator\Date(array('locale' => 'en', 'format' => 'Y-m-d'));
$validator->isValid('123'); // false
$validator->isValid(123); // true
```
Or maybe this is also desired behavior?

here validator ignores everything if data is integer: https://github.com/zendframework/zf2/blob/master/library/Zend/Validator/Date.php#L152-L155

**Comment by adamlundrigan** [comment] 2015-11-06 19:32
This is the intended behaviour.  Integer 123 is interpreted as UNIX epoch time and is converted like so:

```php
return date_create("@$value");
```
([Source](https://github.com/zendframework/zend-validator/blob/33f0141fce05155fb75b5d68fac5856d3a21ebd2/src/Date.php#L152-L155))

So the result is valid.  Alternatively, String 123 is interpreted as a formatted timestamp which must match the format specified (in your case `Y-m-d`)...it doesn't so it's not valid.

**Comment by svycka** [comment] 2015-11-07 08:03
@adamlundrigan if I specify date format I expect that only date in this format will be valid. for example when saving to database will be thrown exception when saving int not Y-m-d

**Comment by svycka** [comment] 2015-11-09 09:24
@adamlundrigan to be more clear imagine situation when you need to validate day of the month 'j' i would create it like this:
```php
$validator = new Validator\Date(['locale' => 'en', 'format' => 'j']);
$validator->isValid(5); // this is true, ok
$validator->isValid(99); // this is also true, this is not what I would expect, month does not have 99 days
```
So I don't get why you closed this. At least this must determine if format specified then validate it for this format not with some exceptions like if it is integer it is valid always..
when validator is used with forms yes value is always string so no problem, but often validators are used with API when data comes from json and it is not converted to string automatically.

**Comment by GeeH** [comment] 2016-06-27 15:51
This issue has been closed as part of the bug migration program as outlined here - http://framework.zend.com/blog/2016-04-11-issue-closures.html

**Closed by GeeH** 2016-06-27 15:51 UTC
Labels: To Be Closed, Validator
